### ISSUE TITLE
"For" loop variable scope

### ISSUE THREAD

**Issue by jonstapleton** [Praxly/praxly.github.io#40]
Variables initialized as part of a "for" loop are global, and should instead be scoped to the "for" loop only. [This program](https://praxly.cs.jmu.edu/main.html#code=for%20(int%20i%20%E2%86%90%200%3B%20i%20%3C%205%3B%20i%20%E2%86%90%20i%20%2B%201)%0A%20%20%20%20print%20i%0Aend%20for%0A%0Aprint%20i%20%20%2F%2F%20this%20line%20should%20throw%20an%20error%0A%0A%2F%2F%20line%208%20throws%20an%20error%2C%20but%20it%20should%20not%0Afor(int%20i%3D0%3Bi%3C2%3Bi%3Di%2B1)%0A%20%20%20%20print%20i%0Aend%20for%0A) demonstrates the issue.

**Comment by ChrisMayfield** [comment]
Thank you! The fix was deployed today. (forgot to reference this issue in the commit message)
